service: youtube-audio-worker

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 300
  memorySize: 1024
  environment:
    S3_BUCKET: ${env:S3_BUCKET}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${env:S3_BUCKET}/*"

functions:
  downloadAudio:
    handler: lambda-youtube-worker.handler
    events:
      - http:
          path: /api/download-audio
          method: post
          cors: true
      - http:
          path: /api/download-audio
          method: options
          cors: true

plugins:
  - serverless-offline
